config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mathjax 'mathjax'

  mount ActionCable.server, at: '/cable'

  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

  root 'packages#index'

  resources :packages do
    member do
      put 'enroll'
      put 'rate'
      get 'users'
    end

    resources :announcements
    resources :classrooms do
      member do
        put 'prepare_presentation'
        put 'initialize_live'
      end
      resources :chats
    end
    resources :topics do
      resources :replies
    end
    resources :lessons
    resources :tests do
      member do
        put 'start'
        get 'attend'
        get 'review'
        put 'select'
        put 'complete'
        get 'result'
        delete 'reattempt'
      end
    end
  end

  post '/images/upload', 'images#upload', defaults: { format: 'json' }

  get 'about', to: 'static#about'
  get 'privacy', to: 'static#privacy'
  get 'terms', to: 'static#terms'
  get 'blog', to: 'posts#index'

  namespace :api, defaults: { format: :json } do
    resources :users
    resources :packages
  end

  resources 'sessions', only: [:new, :create, :destroy]
  resources :users do
    member do
      put :shadow
    end
  end
  resources :posts

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'register', to: 'users#new'
  post 'register', to: 'users#create'

  post 'start_payment', to: 'payments#start'
  post 'verify_payment', to: 'payments#verify'

  namespace :admin do
    root 'packages#index'
    resources :packages do
      member do
        put :enroll
        delete :unenroll
      end
      resources :announcements
      resources :classrooms
      resources :lessons do
        member do
          put 'update_video_uuid'
          delete 'delete_video'
        end
      end
      resources :tests do
        member do
          get 'questions'
          put 'add_question'
          put 'remove_question'
          get 'select_questions'
          get 'preview'
        end
      end
    end
    resources :questions do
      member do
        put 'update_explanation_uuid'
        delete 'destroy_explanation_uuid'
      end
    end
    resources :posts
    resources :users
  end
end

app/models/announcement.rb
# == Schema Information
#
# Table name: announcements
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  content    :text(65535)      not null
#  package_id :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Announcement < ApplicationRecord
  acts_as_taggable

  default_scope { order(created_at: :desc) }

  self.per_page = 12

  belongs_to :package

  validates :package, presence: true
end

app/controllers/admin/announcements_controller.rb
class Admin::AnnouncementsController < AdminController
  before_action :load_package
  before_action :load_announcement, only: [:edit, :update, :destroy]

  def new
    @announcement = @package.announcements.new
  end

  def edit
  end

  def create
    @announcement = @package.announcements.new(announcement_params)
    if @announcement.save
      flash[:notice] = t('messages.created')
      redirect_to package_announcements_path(@package)
    else
      flash.now[:error] = @announcement.errors.full_messages.first
      render :new
    end
  end

  def update
    if @announcement.update_attributes(announcement_params.merge(package: @package))
      flash[:notice] = t('messages.updated')
      redirect_to package_announcements_path(@package)
    else
      flash.now[:error] = @announcement.errors.full_messages.first
      render :edit
    end
  end

  def destroy
    @announcement.destroy
    flash[:notice] = t('messages.deleted')
    redirect_to package_announcements_path(@package)
  end

  private
  def load_package
    @package = Package.unscoped.find(params[:package_id])
  end

  def load_announcement
    @announcement = @package.announcements.find(params[:id])
  end

  def announcement_params
    params.require(:announcement).permit(:title, :content, tag_list: [])
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :require_user
  before_action :require_enrolled_user
  before_action :load_package

  def index
    @announcements = @package.announcements
    if params[:tag].present?
      @announcements = @announcements.tagged_with([params[:tag]], any: true)
    end
    @announcements = @announcements.paginate(page: params[:page])
    @tags = @package.announcements.tag_counts.sort_by(&:count).reverse
  end

  private
  def load_package
    @package = Package.unscoped.find(params[:package_id])
    @meta_title = @package.name
  end
end

app/helpers/admin/announcements_helper.rb
module Admin::AnnouncementsHelper
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/index.html.erb
<div class="page-header">
  <h2><%= @package.name %></h2>
</div>
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <%= link_to t('menus.home'), root_path %>
  </li>
  <li class="breadcrumb-item">
    <%= link_to @package.name, package_path(@package) %>
  </li>
  <li class="breadcrumb-item active">
    <%= t('packages.announcements') %>
  </li>
</ol>

<%= render 'packages/menu' %>

<div class="row">
  <div class="col-sm-9">
    <% if admin? %>
      <div class="col-sm-12 mb-4 text-right">
        <%= link_to t('admin.announcements.new'), new_admin_package_announcement_path(@package), class: 'btn btn-primary' %>
      </div>
    <% end %>
    <% if @announcements.present? %>
      <% @announcements.each do |announcement| %>
        <div class="card mb-4">
          <div class="card-body">
            <div class="card-text">
              <div class="card-title">
                <h4><%= announcement.title %></h4>
              </div>
              <p>
                <%= raw announcement.content %>
                <small class="text-info">
                  <%= t('messages.posted', time: time_ago_in_words(announcement.created_at)) %>
                </small>
              </p>
              <% if admin? %>
                <p>
                  <%= link_to t('actions.edit'), edit_admin_package_announcement_path(@package, announcement),
                              class: 'btn btn-secondary' %>
                  <%= link_to t('actions.delete'), admin_package_announcement_path(@package, announcement),
                              method: :delete, class: 'btn btn-danger',
                              data: { confirm: t('messages.confirm') } %>
                </p>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="float-right">
        <%= will_paginate @announcements, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
      </div>
    <% else %>
      <div class="alert alert-warning">
        <%= t('messages.no_announcements') %>
      </div>
    <% end %>
  </div>
  <div class="col-sm-3">
    <%= link_to 'All', package_announcements_path(@package, tag: nil, page: params[:page]), class: "badge no-link #{ params[:tag].blank? ? 'badge-primary' : 'badge-light' }" %>
    <% @tags.each do |tag| %>
      <%= link_to tag.name, package_announcements_path(@package, tag: tag.name),
                  class: "badge no-link #{ tag.name == params[:tag] ? 'badge-primary' : 'badge-light' }" %>
    <% end %>
  </div>
</div>