config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mathjax 'mathjax'

  mount ActionCable.server, at: '/cable'

  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

  root 'packages#index'

  resources :packages do
    member do
      put 'enroll'
      put 'rate'
      get 'users'
    end

    resources :announcements
    resources :classrooms do
      member do
        put 'prepare_presentation'
        put 'initialize_live'
      end
      resources :chats
    end
    resources :topics do
      resources :replies
    end
    resources :lessons
    resources :tests do
      member do
        put 'start'
        get 'attend'
        get 'review'
        put 'select'
        put 'complete'
        get 'result'
        delete 'reattempt'
      end
    end
  end

  post '/images/upload', 'images#upload', defaults: { format: 'json' }

  get 'about', to: 'static#about'
  get 'privacy', to: 'static#privacy'
  get 'terms', to: 'static#terms'
  get 'blog', to: 'posts#index'

  namespace :api, defaults: { format: :json } do
    resources :users
    resources :packages
  end

  resources 'sessions', only: [:new, :create, :destroy]
  resources :users do
    member do
      put :shadow
    end
  end
  resources :posts

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'register', to: 'users#new'
  post 'register', to: 'users#create'

  post 'start_payment', to: 'payments#start'
  post 'verify_payment', to: 'payments#verify'

  namespace :admin do
    root 'packages#index'
    resources :packages do
      member do
        put :enroll
        delete :unenroll
      end
      resources :announcements
      resources :classrooms
      resources :lessons do
        member do
          put 'update_video_uuid'
          delete 'delete_video'
        end
      end
      resources :tests do
        member do
          get 'questions'
          put 'add_question'
          put 'remove_question'
          get 'select_questions'
          get 'preview'
        end
      end
    end
    resources :questions do
      member do
        put 'update_explanation_uuid'
        delete 'destroy_explanation_uuid'
      end
    end
    resources :posts
    resources :users
  end
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  content    :text(65535)      not null
#  package_id :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Topic < ApplicationRecord
  default_scope { order(created_at: :desc) }

  self.per_page = 10

  belongs_to :package

  validates :package, presence: true

  belongs_to :user

  has_many :replies
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < AdminController
  before_action :load_topic, only: [:edit, :update, :destroy]

  def new
    @topic = Topic.new
  end

  def edit
  end

  def create
    @topic = Topic.new(post_params)
    if @topic.save
      flash[:notice] = t('messages.created')
      redirect_to topics_path
    else
      flash.now[:error] = @topic.errors.full_messages.first
      render :new
    end
  end

  def update
    if @topic.update_attributes(post_params)
      flash[:notice] = t('messages.updated')
      redirect_to posts_path
    else
      flash.now[:error] = @topic.errors.full_messages.first
      render :edit
    end
  end

  def destroy
    @topic.destroy
    flash[:notice] = t('messages.deleted')
    redirect_to posts_path
  end

  private
  def load_topic
    @topic = Topic.find(params[:id])
  end

  def post_params
    params.require(:topic).permit(:title, :content)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :require_user
  before_action :require_enrolled_user
  before_action :load_package

  def index
    @topics = @package.topics.paginate(page: params[:page])
  end

  def new
    @topic = @package.topics.new
  end

  def show
    @topic = @package.topics.find(params[:id])
    @replies = @topic.replies.paginate(page: params[:page])
  end

  def create
    @topic = @package.topics.new(topics_params.merge(user_id: current_user.id))
    if @topic.save
      flash[:notice] = t('messages.created')
      redirect_to package_topic_path(@package, @topic)
    else
      flash.now[:error] = @topic.errors.full_messages.first
      render :new
    end
  end

  def destroy
    @topic = @package.topics.find(params[:id])
    if current_user.admin?
      @topic.destroy
      flash[:notice] = t('messages.deleted')
    else
      flash[:error] = t('messages.unauthorized')
    end
    redirect_to package_topics_path(@package)
  end

  private
  def load_package
    @package = Package.unscoped.find(params[:package_id])
    @meta_title = @package.name
  end

  def topics_params
    params.require(:topic).permit(:title, :content)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_topic.html.erb
<%= form_for [@package, @topic] do |topic_form| %>
  <div class="form-group row">
    <div class="col-sm-2">
      <%= topic_form.label t('topics.title'), class: 'col-form-label' %>
    </div>
    <div class="col-sm-10">
      <%= topic_form.text_field :title, class: 'form-control', required: true %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-2">
      <%= topic_form.label t('topics.content'), class: 'col-form-label' %>
    </div>
    <div class="col-sm-10">
      <%= topic_form.text_area :content, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-10 ml-auto">
      <%= topic_form.submit t('actions.create'), class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/topics/index.html.erb
<div class="page-header">
  <h2><%= @package.name %></h2>
</div>

<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <%= link_to t('menus.home'), root_path %>
  </li>
  <li class="breadcrumb-item">
    <%= link_to @package.name, package_path(@package) %>
  </li>
  <li class="breadcrumb-item active">
    <%= t('packages.discussion') %>
  </li>
</ol>

<%= render 'packages/menu' %>

<div class="col-sm-12 mb-4 text-right">
  <%= link_to t('topics.new'), new_package_topic_path(@package), class: 'btn btn-primary' %>
</div>

<% if @topics.present? %>
  <ul class="list-group">
    <% @topics.each do |topic| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to topic.title, package_topic_path(@package, topic) %>
        <span class="badge badge-primary badge-pill">
          <%= topic.replies.count %>
        </span>
      </li>
    <% end %>
  </ul>
  <div class="float-right">
    <%= will_paginate @topics, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
  </div>
<% else %>
  <div class="alert alert-warning">
    <%= t('messages.no_topics') %>
  </div>
<% end %>

app/views/topics/new.html.erb
<div class="page-header">
  <h2><%= @package.name %></h2>
</div>

<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <%= link_to t('menus.home'), root_path %>
  </li>
  <li class="breadcrumb-item">
    <%= link_to @package.name, package_path(@package) %>
  </li>
  <li class="breadcrumb-item active">
    <%= t('packages.discussion') %>
  </li>
</ol>

<%= render 'packages/menu' %>

<div class="page-header">
  <h4><%= t('topics.new') %></h4>
</div>

<%= render 'topic' %>

app/views/topics/show.html.erb
<div class="page-header">
  <h2><%= @package.name %></h2>
</div>

<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <%= link_to t('menus.home'), root_path %>
  </li>
  <li class="breadcrumb-item">
    <%= link_to @package.name, package_path(@package) %>
  </li>
  <li class="breadcrumb-item">
    <%= link_to t('packages.discussion'), package_topics_path(@package) %>
  </li>
  <li class="breadcrumb-item active">
    <%= truncate(@topic.title) %>
  </li>
</ol>

<%= render 'packages/menu' %>

<div class="card mb-4">
  <div class="card-body">
    <div class="card-text">
      <div class="page-header">
        <h4><%= @topic.title %></h4>
      </div>
      <p>
        <%= raw @topic.content %>
      </p>
      <p>
        <small class="text-info">
          <%= t('messages.posted', time: time_ago_in_words(@topic.created_at)) %> by
          <%= @topic.user.name %>
        </small>
      </p>
      <p>
        <%= link_to t('actions.reply'), new_package_topic_reply_path(@package, @topic),
                    class: 'btn btn-primary' %>
        <% if admin? %>
          <%= link_to t('actions.delete'), package_topic_path(@package, @topic), method: :delete,
                      class: 'btn btn-danger', data: { confirm: t('messages.confirm') } %>
        <% end %>
      </p>
    </div>
  </div>
</div>

<% @replies.each do |reply| %>
  <div class="card mb-4">
    <div class="card-body">
      <div class="card-text">
        <p>
          <%= raw reply.content %>
        </p>
        <p>
          <small class="text-info">
            <%= t('messages.posted', time: time_ago_in_words(reply.created_at)) %> by
            <%= reply.user.name %>
          </small>
        </p>
        <p>
          <% if admin? %>
            <%= link_to t('actions.delete'), package_topic_reply_path(@package, @topic, reply), method: :delete,
                        class: 'btn btn-danger btn-sm', data: { confirm: t('messages.confirm') } %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
<% end %>

<div class="float-right">
  <%= will_paginate @replies, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
</div>