config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mathjax 'mathjax'

  mount ActionCable.server, at: '/cable'

  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

  root 'packages#index'

  resources :packages do
    member do
      put 'enroll'
      put 'rate'
      get 'users'
    end

    resources :announcements
    resources :classrooms do
      member do
        put 'prepare_presentation'
        put 'initialize_live'
      end
      resources :chats
    end
    resources :topics do
      resources :replies
    end
    resources :lessons
    resources :tests do
      member do
        put 'start'
        get 'attend'
        get 'review'
        put 'select'
        put 'complete'
        get 'result'
        delete 'reattempt'
      end
    end
  end

  post '/images/upload', 'images#upload', defaults: { format: 'json' }

  get 'about', to: 'static#about'
  get 'privacy', to: 'static#privacy'
  get 'terms', to: 'static#terms'
  get 'blog', to: 'posts#index'

  namespace :api, defaults: { format: :json } do
    resources :users
    resources :packages
  end

  resources 'sessions', only: [:new, :create, :destroy]
  resources :users do
    member do
      put :shadow
    end
  end
  resources :posts

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'register', to: 'users#new'
  post 'register', to: 'users#create'

  post 'start_payment', to: 'payments#start'
  post 'verify_payment', to: 'payments#verify'

  namespace :admin do
    root 'packages#index'
    resources :packages do
      member do
        put :enroll
        delete :unenroll
      end
      resources :announcements
      resources :classrooms
      resources :lessons do
        member do
          put 'update_video_uuid'
          delete 'delete_video'
        end
      end
      resources :tests do
        member do
          get 'questions'
          put 'add_question'
          put 'remove_question'
          get 'select_questions'
          get 'preview'
        end
      end
    end
    resources :questions do
      member do
        put 'update_explanation_uuid'
        delete 'destroy_explanation_uuid'
      end
    end
    resources :posts
    resources :users
  end
end

app/models/lesson.rb
# == Schema Information
#
# Table name: lessons
#
#  id          :integer          not null, primary key
#  title       :string(255)      not null
#  description :text(65535)
#  video_uuid  :string(255)
#  package_id  :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Lesson < ApplicationRecord
  belongs_to :package

  validates :title, presence: true
  validates :package, presence: true

  self.per_page = 12
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < AdminController
  before_action :load_package
  before_action :load_lesson, only: [:edit, :update, :destroy, :update_video_uuid, :delete_video]

  def new
    @lesson = @package.lessons.new
  end

  def edit
  end

  def create
    @lesson = @package.lessons.new(lesson_params)
    if @lesson.save
      flash[:notice] = t('messages.created')
      redirect_to package_lessons_path(@package)
    else
      flash.now[:error] = @lesson.errors.full_messages.first
      render :new
    end
  end

  def update
    if @lesson.update_attributes(lesson_params.merge(package: @package))
      flash[:notice] = t('messages.updated')
      redirect_to package_lessons_path(@package)
    else
      flash.now[:error] = @lesson.errors.full_messages.first
      render :new
    end
  end

  def destroy
    @lesson.destroy
    flash[:notice] = t('messages.deleted')
    redirect_to package_lessons_path(@package)
  end

  private
  def load_package
    @package = Package.unscoped.find(params[:package_id])
  end

  def load_lesson
    @lesson = @package.lessons.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :description, :video_uuid)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :require_user
  before_action :require_enrolled_user
  before_action :load_package

  def index
    @lessons = @package.lessons.paginate(page: params[:page])
  end

  private
  def load_package
    @package = Package.unscoped.find(params[:package_id])
    @meta_title = @package.name
  end
end

app/helpers/admin/lessons_helper.rb
module Admin::LessonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/index.html.erb
<div class="page-header">
  <h2><%= @package.name %></h2>
</div>
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <%= link_to t('menus.home'), root_path %>
  </li>
  <li class="breadcrumb-item">
    <%= link_to @package.name, package_path(@package) %>
  </li>
  <li class="breadcrumb-item active">
    <%= t('packages.lessons') %>
  </li>
</ol>

<%= render 'packages/menu' %>

<div class="row">
  <% if admin? %>
    <div class="col-sm-12 mb-4 text-right">
      <%= link_to t('admin.lessons.new'), new_admin_package_lesson_path(@package), class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<% if @lessons.present? %>
  <div class="row">
    <% @lessons.each do |lesson| %>
      <div class="col-sm-4">
        <div class="card mb-4">
          <div class="card-body">
            <div class="card-text">
              <% if lesson.video_uuid.present? %>
                <iframe src='https://www.youtube.com/embed/<%= lesson.video_uuid  %>?rel=0'
                        frameborder='0' allowfullscreen>
                </iframe>
              <% else %>
                <%= image_tag 'video_unavailable.gif', width: 250, height: 200, class: 'float-left mr-4' %>
              <% end %>
              <h2 class="card-title">
                <%= lesson.title %>
              </h2>
              <p><%= raw lesson.description %></p>
            </div>
            <% if admin? %>
              <%= link_to t('actions.edit'), edit_admin_package_lesson_path(@package, lesson),
                          class: 'btn btn-secondary' %>
              <%= link_to t('actions.delete'), admin_package_lesson_path(@package, lesson),
                          method: :delete, class: 'btn btn-danger',
                          data: { confirm: t('messages.confirm') } %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="float-right">
    <%= will_paginate @lessons, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
  </div>
<% else %>
  <div class="col-12 alert alert-warning" role="alert">
    <%= t('messages.no_lessons') %>
  </div>
<% end %>