config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mathjax 'mathjax'

  mount ActionCable.server, at: '/cable'

  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

  root 'packages#index'

  resources :packages do
    member do
      put 'enroll'
      put 'rate'
      get 'users'
    end

    resources :announcements
    resources :classrooms do
      member do
        put 'prepare_presentation'
        put 'initialize_live'
      end
      resources :chats
    end
    resources :topics do
      resources :replies
    end
    resources :lessons
    resources :tests do
      member do
        put 'start'
        get 'attend'
        get 'review'
        put 'select'
        put 'complete'
        get 'result'
        delete 'reattempt'
      end
    end
  end

  post '/images/upload', 'images#upload', defaults: { format: 'json' }

  get 'about', to: 'static#about'
  get 'privacy', to: 'static#privacy'
  get 'terms', to: 'static#terms'
  get 'blog', to: 'posts#index'

  namespace :api, defaults: { format: :json } do
    resources :users
    resources :packages
  end

  resources 'sessions', only: [:new, :create, :destroy]
  resources :users do
    member do
      put :shadow
    end
  end
  resources :posts

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'register', to: 'users#new'
  post 'register', to: 'users#create'

  post 'start_payment', to: 'payments#start'
  post 'verify_payment', to: 'payments#verify'

  namespace :admin do
    root 'packages#index'
    resources :packages do
      member do
        put :enroll
        delete :unenroll
      end
      resources :announcements
      resources :classrooms
      resources :lessons do
        member do
          put 'update_video_uuid'
          delete 'delete_video'
        end
      end
      resources :tests do
        member do
          get 'questions'
          put 'add_question'
          put 'remove_question'
          get 'select_questions'
          get 'preview'
        end
      end
    end
    resources :questions do
      member do
        put 'update_explanation_uuid'
        delete 'destroy_explanation_uuid'
      end
    end
    resources :posts
    resources :users
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  content    :text(65535)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  acts_as_taggable

  default_scope { order(created_at: :desc) }

  self.per_page = 5
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  before_action :load_post, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = t('messages.created')
      redirect_to posts_path
    else
      flash.now[:error] = @post.errors.full_messages.first
      render :new
    end
  end

  def update
    if @post.update_attributes(post_params)
      flash[:notice] = t('messages.updated')
      redirect_to posts_path
    else
      flash.now[:error] = @post.errors.full_messages.first
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = t('messages.deleted')
    redirect_to posts_path
  end

  private
  def load_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, tag_list: [])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @meta_title = meta_title t('meta_title')
    @posts = Post
    if params[:tag].present?
      @posts = @posts.tagged_with([params[:tag]], any: true)
    end
    @posts = @posts.paginate(page: params[:page])
    @tags = Post.tag_counts.sort_by(&:count).reverse
  end

  def show
    @post = Post.find(params[:id])
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="page-header">
  <h2><%= t('headings.blog') %></h2>
</div>
<div class="row">
  <div class="col-sm-9">
    <% if admin? %>
      <div class="col-sm-12 mb-4 text-right">
        <%= link_to t('admin.posts.new'), new_admin_post_path, class: 'btn btn-primary' %>
      </div>
    <% end %>
    <% if @posts.present? %>
      <% @posts.each do |post| %>
        <div class="card mb-4">
          <div class="card-body">
            <div class="page-header">
              <h4><%= link_to post.title, post_path(post) %></h4>
            </div>
            <p>
              <%= truncate(sanitize(post.content, tags: []), length: 200) %>
            </p>
            <p>
              <small class="text-info">
                <%= t('messages.posted', time: time_ago_in_words(post.created_at)) %>
              </small>
            </p>
          </div>
        </div>
      <% end %>
      <div class="float-right">
        <%= will_paginate @posts, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
      </div>
    <% else %>
      <div class="alert alert-warning">
        <%= t('messages.no_posts') %>
      </div>
    <% end %>
  </div>
  <div class="col-sm-3">
    <%= link_to 'All', blog_path(tag: nil, page: params[:page]), class: "badge no-link #{ params[:tag].blank? ? 'badge-primary' : 'badge-light' }" %>

    <% @tags.each do |tag| %>
      <%= link_to tag.name, blog_path(tag: tag.name),
                  class: "badge no-link #{ tag.name == params[:tag] ? 'badge-primary' : 'badge-light' }" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="page-header">
  <h2><%= t('headings.blog') %></h2>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="card mb-4">
      <div class="card-body">
        <div class="page-header">
          <h4><%= link_to @post.title %></h4>
        </div>
        <p>
          <%= raw @post.content %>
        </p>
        <p>
          <small class="text-info">
            <%= t('messages.posted', time: time_ago_in_words(@post.created_at)) %>
          </small>
        </p>
        <% if admin? %>
          <p>
            <%= link_to edit_admin_post_path(@post), class: 'text-secondary no-link ml-2', title: t('actions.edit') do %>
              <%= fa_icon 'edit 2x' %>
            <% end %>
            <%= link_to admin_post_path(@post), method: :delete,
                        class: 'text-danger no-link', title: t('actions.delete'),
                        data: { confirm: t('messages.confirm') } do %>
              <%= fa_icon 'trash 2x' %>
            <% end %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>